name: "CI-CD"

on:
  push:
    branches:
      - "master"

jobs:
  build-test-deploy:
    name: Build, test, and deploy the demo on firebase
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"

      - name: Install Yarn
        run: npm install -g yarn

      - uses: actions/checkout@v2

      - name: "Install dependency"
        run: yarn install --frozen-lockfile

      - name: "Build the library"
        run: yarn ci:build:library

      - name: "Build the demo app"
        run: yarn ci:build:app

      - name: "Test the library"
        run: yarn ci:test:library

      - name: "Test the demo app"
        run: yarn ci:test:app

      - name: "Publish the demo on firebase"
        run: |
          yarn global add firebase-tools
          firebase --token ${{ secrets.FIREBASE_TOKEN }} deploy --only hosting --project ngx-image-compress

      - name: "Deploy to Netlify"
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './dist/ngx-image-compress-demo'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
